---
  syncPeriodSecs:
    min: 1
    max: 60
    default: 60
  journal_commitIntervalMs:
    min: 1
    max: 500
    default: 100
  mmapv1_smallFiles:
    range:
      - true
      - false
    default: false
  wiredTiger_cacheSizeGB:
    min: 0.25
    max: 5
    float: yes
    default: 3.5
    bucket_num: 10
  wiredTiger_journalCompressor:
    range:
      - none
      - snappy
      - zlib
    default: snappy
  wiredTiger_blockCompressor:
    range:
      - none
      - snappy
      - zlib
    default: snappy
  wiredTiger_prefixCompression:
    range:
      - true
      - false
    default: true
  wiredTiger_netCompressor:
    range:
      - disabled
      - snappy
      - zlib
    default: snappy
  wiredTiger_serviceExecutor:
    range:
      - synchronous
      - adaptive
    default: synchronous
  net_maxIncomingConnections:
    min: 128
    max: 1024
    default: 819
  processManagement_fork:
    range:
      - true
      - false
    default: true
  operationProfiling_slowOpThresholdMs:
    min: 70
    max: 170
    default: 100
  operationProfiling_mode:
    range:
      - 'off'
      - 'slowOp'
      - 'all'
    default: 'off'


