---
# - hosts: "{{host}}"
- hosts: "{{host}}"
    # - v-two
  gather_facts: no
  vars:
    # required extra vars:
    #   - host
    #   - target
    #   - project_dir
    #   - task_id
    #   - task_step
    #   - workload_name
    #   - task_name
    #   - task_rep
    #   - workload_path
    #   - n_client
    #   - user
    #   - pwd
    db_name: redis
    apt_requirements:
      # - openjdk-8-jdk
    home_dir: "{{project_dir}}/environment/target/{{db_name}}"
    target_ip: "{{hostvars[target].ansible_ssh_host}}"
    target_port: 6379
    local_ycsb_zip: ../ycsb-redis-binding-0.15.0.tar.gz
    local_result_dir: "{{home_dir}}/results/{{task_name}}"
    local_ycsb_workload: "{{workload_path}}"
    local_redis_cli_path: "{{home_dir}}/{{db_name}}-cli"
    ycsb_bin: "{{home_dir}}/ycsb-redis-binding-0.15.0/bin/ycsb"
    ycsb_workload: "{{workload_path}}"
    load_result_path: "{{home_dir}}/load_result"
    load_err_path: "{{home_dir}}/load_err"
    run_result_path: "{{home_dir}}/run_result"
    run_err_path: "{{home_dir}}/run_err"
    n_threads: "{{n_client}}"
    ansible_sudo_pass: "{{pwd}}"
  remote_user: "{{user}}"
  pre_tasks:
    # - name: ensure jdk
    #   apt:
    #     name: "{{apt_requirements}}"
    #   become: yes
    - name: ensure folder
      file:
        path: "{{home_dir}}"
        state: directory
        recurse: yes
    - name: copy ycsb package
      copy:
        src: "{{local_ycsb_zip}}"
        dest: "{{home_dir}}/ycsb.zip"
    - name: unarchive ycsb
      unarchive:
        dest: "{{home_dir}}"
        src: "{{home_dir}}/ycsb.zip"
        remote_src: yes
    - name: copy ycsb workload # template?
      copy:
        src: "{{local_ycsb_workload}}"
        dest: "{{ycsb_workload}}"
    - name: copy redis6-cli # for ping test
      copy:
        src: "{{local_redis_cli_path}}"
        dest: "{{home_dir}}/redis6-cli"
        mode: a+x
  tasks:
    - name: ping redis # test if redis server is fully set up
      shell: "{{home_dir}}/redis6-cli -h {{target_ip}} -p {{target_port}} ping"
      retries: 10
      delay: 6
    - name: ycsb load
      shell: "python2 {{ycsb_bin}} load redis -P {{ycsb_workload}} -p redis.host={{target_ip}} -p redis.port={{target_port}} -s 1>{{load_result_path}} 2>{{load_err_path}}"
    - name: fetch load result
      fetch:
        src: "{{load_result_path}}"
        dest: "{{local_result_dir}}/{{task_id}}_load_result_{{workload_name}}_{{task_step}}_{{task_rep}}"
        flat: yes
    - name: fetch load err
      fetch:
        src: "{{load_err_path}}"
        dest: "{{local_result_dir}}/{{task_id}}_load_err_{{workload_name}}_{{task_step}}_{{task_rep}}"
        flat: yes
    - name: ycsb run
      shell: "python2 {{ycsb_bin}} run redis -P {{ycsb_workload}} -threads {{n_threads}} -p redis.host={{target_ip}} -p redis.port={{target_port}} -s 1>{{run_result_path}} 2>{{run_err_path}}"
    - name: fetch run result
      fetch:
        src: "{{run_result_path}}"
        dest: "{{local_result_dir}}/{{task_id}}_run_result_{{workload_name}}_{{task_step}}_{{task_rep}}"
        flat: yes
    - name: fetch run err
      fetch:
        src: "{{run_err_path}}"
        dest: "{{local_result_dir}}/{{task_id}}_run_err_{{workload_name}}_{{task_step}}_{{task_rep}}"
        flat: yes
